apiVersion: 1 # Grafana API 버전

datasources: # Prometheus 데이터 소스에 대한 설정
  - name: Prometheus
    type: prometheus
    access: proxy # 데이터 소스에 대한 액세스 방법
    orgId: 1      # Grafana 조직의 ID
    url: http://prometheus:9090
    isDefault: true # 데이터 소스를 기본 데이터 소스로 설정 할지에 대한 여부
    version: 1
    editable: true # 데이터 소스를 사용자가 편집할 수 있는지 여부
    # basicAuth: false   # Grafana가 Prometheus와 통신할 때 사용자 이름과 비밀번호를 제공하지 않도록 설정