FROM node:16-alpine as builder
WORKDIR /frontend
COPY ../frontend .
RUN npm cache clear --force && npm i
RUN npm install recoil
RUN npm install framer-motion
RUN npm install -g vite
RUN npm run build

FROM nginx
COPY --from=builder /frontend/dist /var/www/frontend
RUN rm /etc/nginx/nginx.conf
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf