name: Deploy to EC2 on Push

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Create /tmp directory
      run: mkdir -p /tmp

    - name: Save private key
      run: echo "${{ secrets.EC2_PRIVATE_KEY }}" > /tmp/private_key.pem

    - name: Set key file permissions
      run: chmod 600 /tmp/private_key.pem

    - name: Deploy to EC2
      run: |
        ssh -i /tmp/private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "~/deploy-script.sh"
